sudo: false
language: python
matrix:
  include:
    - python: '3.4'
      env: TOXENV=py34-django18
    - python: '3.5'
      env: TOXENV=py35-django18

    - python: '3.4'
      env: TOXENV=py34-django110
    - python: '3.5'
      env: TOXENV=py35-django110

    - python: '3.4'
      env: TOXENV=py34-django111
    - python: '3.5'
      env: TOXENV=py35-django111
    - python: '3.6'
      env: TOXENV=py36-django111

    - python: '3.4'
      env: TOXENV=py34-django20
    - python: '3.5'
      env: TOXENV=py35-django20
    - python: '3.6'
      env: TOXENV=py36-django20

install:
  - pip install -U pip wheel setuptools
  - pip install tox tox-travis
  - pip install pytest-cov python-coveralls
  
script: tox

after_success:
- pip install -e .
- py.test --cov=. --cov-report=term-missing tests
- coveralls
